# -*- coding: utf-8 -*-
"""Medical_Img_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9-VWr3vqpczXu_HErAMXIgVAo43oJTn

# SETUP INSTRUCTIONS:
# 1. Upload dataset folder to Google Drive: MyDrive/skin_cancer_dataset
# 2. Open Colab
# 3. Run The First 3 Cells Only Once In Each Session
# 4. Dataset will be loaded after this step.

# Library Imports Section
"""

# Load All The Libraries HERE! (Do Not Duplicate Plz)
import pandas as pd
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from skimage.feature import graycomatrix, graycoprops, local_binary_pattern
from scipy.ndimage import gaussian_filter
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.feature_selection import SelectKBest, f_classif
from imblearn.over_sampling import SMOTE
import seaborn as sns

# Dataset Setup (Local Version)

import pandas as pd
import os

# 📌 حطي هنا الباث عندك
data_path = r"dataset"
# أو لو برا المشروع:
# data_path = r"C:\Users\YourName\Desktop\dataset"

# تحميل الـ CSV
df = pd.read_csv(os.path.join(data_path, "HAM10000_metadata.csv"))
# =========================
# AUTO DATASET SELECTION
# =========================

MIN_SAMPLES_PER_CLASS = 3

class_counts = df["dx"].value_counts()

valid_classes = class_counts[class_counts >= MIN_SAMPLES_PER_CLASS].index

df_filtered = df[df["dx"].isin(valid_classes)].copy()

# fallback لو الداتا قليلة جدًا
if len(df_filtered) == 0:
    print("⚠ Dataset too small, fallback to >=2 samples per class")

    valid_classes = class_counts[class_counts >= 2].index
    df_filtered = df[df["dx"].isin(valid_classes)].copy()

print("Original dataset size:", len(df))
print("Filtered dataset size:", len(df_filtered))
print("Classes used:", df_filtered["dx"].value_counts().to_dict())
# paths للصور
image_base_path_1 = os.path.join(data_path, "HAM10000_images_part_1")
image_base_path_2 = os.path.join(data_path, "HAM10000_images_part_2")

# عرض أول صفوف
print(df_filtered.head())

"""# Loading The Dataset

"""

# Data Frame with Cols: ['lesion_id', 'image_id', 'dx', 'dx_type', 'age', 'sex', 'localization', image_path']

def find_image_path(image_id):
    file_name = image_id + ".jpg"

    path1 = os.path.join(image_base_path_1, file_name)
    path2 = os.path.join(image_base_path_2, file_name)

    if os.path.exists(path1):
        return path1
    elif os.path.exists(path2):
        return path2
    else:
        return None

df_filtered["image_path"] = df_filtered["image_id"].apply(find_image_path) # Add image_path As A Colomn In Data Frame
df_filtered = df_filtered.dropna(subset=["image_path"])

"""# Preprocessing & Filtering

"""

def preprocess_image(image_path):

    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Filters
    gaussian = cv2.GaussianBlur(img, (5, 5), 0)
    median = cv2.medianBlur(img, 5)

    # Hair Removal
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (9, 9))
    blackhat = cv2.morphologyEx(gray, cv2.MORPH_BLACKHAT, kernel)

    _, mask = cv2.threshold(blackhat, 10, 255, cv2.THRESH_BINARY)

    cleaned = cv2.inpaint(img, mask, 1, cv2.INPAINT_TELEA)

    return img, gaussian, median, cleaned

sample_size = min(300, len(df_filtered))
sample_df = df_filtered.sample(min(300, len(df_filtered)), random_state=42)
print("Dataset size:", len(df_filtered))

results = []

for _, row in sample_df.iterrows():

    path = row["image_path"]
    label = row["dx"]

    original, gaussian, median, cleaned = preprocess_image(path)

    results.append({
        "label": label,
        "original": original,
        "gaussian": gaussian,
        "median": median,
        "cleaned": cleaned
    })

# MSE & PSNR Functions
def mse(img1, img2):
    img1 = img1.astype(np.float32)
    img2 = img2.astype(np.float32)
    return np.mean((img1 - img2) ** 2)


def psnr(img1, img2):
    mse_val = mse(img1, img2)
    if mse_val == 0:
        return 100
    return 20 * np.log10(255.0 / np.sqrt(mse_val))

# Numerical Comparison Table
gauss_mse, gauss_psnr = [], []
median_mse, median_psnr = [], []

for r in results:
    orig = r["original"]

    gauss = r["gaussian"]
    med = r["median"]

    gauss_mse.append(mse(orig, gauss))
    gauss_psnr.append(psnr(orig, gauss))

    median_mse.append(mse(orig, med))
    median_psnr.append(psnr(orig, med))


report = pd.DataFrame({
    "Method": ["Gaussian", "Median"],
    "Avg MSE": [np.mean(gauss_mse), np.mean(median_mse)],
    "Avg PSNR": [np.mean(gauss_psnr), np.mean(median_psnr)]
})

report

def show_gallery(results, num_images=5):

    plt.figure(figsize=(15, num_images * 3))

    for i in range(num_images):
        r = results[i]

        # Original
        plt.subplot(num_images, 4, i*4 + 1)
        plt.imshow(r["original"])
        plt.title("Original")
        plt.axis("off")

        # Gaussian
        plt.subplot(num_images, 4, i*4 + 2)
        plt.imshow(r["gaussian"])
        plt.title("Gaussian")
        plt.axis("off")

        # Median
        plt.subplot(num_images, 4, i*4 + 3)
        plt.imshow(r["median"])
        plt.title("Median")
        plt.axis("off")

        # Hair Removed
        plt.subplot(num_images, 4, i*4 + 4)
        plt.imshow(r["cleaned"])
        plt.title("Hair Removed")
        plt.axis("off")

    plt.tight_layout()
    plt.show()

# Show Results Of First N (Default is 5) Random Images

show_gallery(results, num_images=3)

"""# Features Detection"""

def harris_corner_scratch(img, k=0.04, threshold_ratio=0.01):
    img_copy = img.copy()

    # 1. Convert to Grayscale
    gray = cv2.cvtColor(img_copy, cv2.COLOR_RGB2GRAY).astype(np.float32)

    # 2. Compute spatial derivatives (Ix, Iy) using Sobel filter
    Ix = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    Iy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)

    # 3. Compute products of derivatives at each pixel
    Ixx = Ix ** 2
    Iyy = Iy ** 2
    Ixy = Ix * Iy

    # 4. Apply Gaussian blur to compute the sum of products (Structure Tensor components)
    # sigma=1 is a standard choice for the window function
    Sxx = gaussian_filter(Ixx, sigma=1)
    Syy = gaussian_filter(Iyy, sigma=1)
    Sxy = gaussian_filter(Ixy, sigma=1)

    # 5. Compute the Harris response for each pixel
    # R = det(M) - k * (trace(M))^2
    det_M = (Sxx * Syy) - (Sxy ** 2)
    trace_M = Sxx + Syy
    R = det_M - k * (trace_M ** 2)

    # 6. Apply Thresholding to identify corners
    # Any response greater than the ratio * max_response is considered a corner
    R_max = R.max()
    img_copy[R > threshold_ratio * R_max] = [255, 0, 0] # Color the corners RED

    return img_copy

sample_img = results[0]["cleaned"]

thresholds_to_test = [0.01, 0.001, 0.005,0.05]

plt.figure(figsize=(18, 5))

for i, thresh in enumerate(thresholds_to_test):
    corner_img = harris_corner_scratch(sample_img, threshold_ratio=thresh)

    plt.subplot(1, 4, i + 1)
    plt.imshow(corner_img)
    plt.title(f"Custom Harris - Thresh Ratio: {thresh}")
    plt.axis('off')

plt.tight_layout()
plt.show()

BEST_THRESH = 0.001
num_images_to_show = 10

plt.figure(figsize=(12, num_images_to_show * 3))

for i in range(num_images_to_show):
    original_img = results[i]["original"]
    cleaned_img = results[i]["cleaned"]

    corner_img = harris_corner_scratch(cleaned_img, threshold_ratio=BEST_THRESH)

    plt.subplot(num_images_to_show, 2, 2*i + 1)
    plt.imshow(original_img)
    plt.title("Original Lesion")
    plt.axis("off")

    plt.subplot(num_images_to_show, 2, 2*i + 2)
    plt.imshow(corner_img)
    plt.title(f"Custom Harris Corners (Thresh: {BEST_THRESH})")
    plt.axis("off")

plt.tight_layout()
plt.show()

def get_segmentation_mask(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    blurred = cv2.GaussianBlur(gray, (7, 7), 0)
    _, mask = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = np.ones((5,5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel, iterations=2)
    return mask
    return mask

def harris_corner_scratch_with_mask(img, mask, k=0.04, threshold_ratio=0.001):
    img_copy = img.copy()
    gray = cv2.cvtColor(img_copy, cv2.COLOR_RGB2GRAY).astype(np.float32)

    Ix = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    Iy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)

    Ixx, Iyy, Ixy = Ix**2, Iy**2, Ix*Iy

    Sxx = gaussian_filter(Ixx, sigma=1)
    Syy = gaussian_filter(Iyy, sigma=1)
    Sxy = gaussian_filter(Ixy, sigma=1)

    det_M = (Sxx * Syy) - (Sxy ** 2)
    trace_M = Sxx + Syy
    R = det_M - k * (trace_M ** 2)

    R[mask == 0] = 0

    R_max = R.max()
    img_copy[R > threshold_ratio * R_max] = [255, 0, 0]

    return img_copy

# Load a sample image
image_rgb = results[0]["original"]

# Step 1: Segmentation
mask = get_segmentation_mask(image_rgb)
segmented_img = cv2.bitwise_and(image_rgb, image_rgb, mask=mask)

# Step 2: Apply Harris with segmentation mask
final_result = harris_corner_scratch_with_mask(image_rgb, mask)

plt.figure(figsize=(20, 10))

plt.subplot(1, 4, 1)
plt.imshow(image_rgb)
plt.title("1. Original Image")
plt.axis('off')

plt.subplot(1, 4, 2)
plt.imshow(mask, cmap='gray')
plt.title("2. Segmentation Mask")
plt.axis('off')

plt.subplot(1, 4, 3)
plt.imshow(segmented_img)
plt.title("3. Segmented Lesion")
plt.axis('off')

plt.subplot(1, 4, 4)
plt.imshow(final_result)
plt.title("4. Harris on Lesion Only")
plt.axis('off')

plt.tight_layout()
plt.show()

""" MultiScale Analysis( Gaussian/Laplacian Pyramid )

"""

def gaussian_pyramid(img, levels=4):
    gp = [img.copy()]

    temp = img.copy()
    for _ in range(levels):
        temp = cv2.pyrDown(temp)
        gp.append(temp)

    return gp

def laplacian_pyramid(gp):
    lp = []

    for i in range(len(gp)-1):
        up = cv2.pyrUp(gp[i+1])
        up = cv2.resize(up, (gp[i].shape[1], gp[i].shape[0]))

        lap = cv2.subtract(gp[i].astype(np.float32),
                           up.astype(np.float32))
        lp.append(lap)

    return lp

def show_pyramid(pyramid, title="Pyramid"):
    plt.figure(figsize=(15,4))

    for i in range(len(pyramid)):
        img = pyramid[i]

        img = np.abs(img)
        img = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX)
        img = img.astype(np.uint8)

        plt.subplot(1, len(pyramid), i+1)
        plt.imshow(img, cmap='gray' if len(img.shape)==2 else None)
        plt.title(f"Level {i}")
        plt.axis("off")

    plt.suptitle(title)
    plt.show()

def scale_space_analysis(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY) if len(img.shape)==3 else img

    scales = [1.0, 0.75, 0.5]

    plt.figure(figsize=(12,4))

    for i, s in enumerate(scales):
        resized = cv2.resize(gray, None, fx=s, fy=s)
        edges = cv2.Canny(resized, 100, 200)

        plt.subplot(1, len(scales), i+1)
        plt.imshow(edges, cmap='gray')
        plt.title(f"Scale {s}")
        plt.axis("off")

    plt.show()

def multi_scale_detection(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    scales = [1.0, 0.75, 0.5]

    plt.figure(figsize=(12,4))

    for i, s in enumerate(scales):
        resized = cv2.resize(gray, None, fx=s, fy=s)
        blur = cv2.GaussianBlur(resized, (5,5), 0)
        edges = cv2.Canny(blur, 50, 150)

        plt.subplot(1, len(scales), i+1)
        plt.imshow(edges, cmap='gray')
        plt.title(f"Scale {s}")
        plt.axis("off")

    plt.show()

for i in range(3):

    print(f"\n===== Image {i} ({results[i]['label']}) =====")

    img = results[i]["cleaned"].astype(np.uint8)

    # Gaussian Pyramid
    gp = gaussian_pyramid(img, levels=4)
    show_pyramid(gp, "Gaussian Pyramid")

    # Laplacian Pyramid
    lp = laplacian_pyramid(gp)
    show_pyramid(lp, "Laplacian Pyramid")

    # Scale-space
    scale_space_analysis(img)

    # Multi-scale detection
    multi_scale_detection(img)

"""# Feature Extraction Module

### SIFT Feature Extraction & Matching
"""

sift = cv2.SIFT_create()

def get_sift(img, use_mask=False):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    mask = get_segmentation_mask(img) if use_mask else None
    kp, desc = sift.detectAndCompute(gray, mask)
    return kp, desc

def get_matches(desc1, desc2, ratio=0.75):
    matches = cv2.BFMatcher(cv2.NORM_L2).knnMatch(desc1, desc2, k=2)
    good    = []
    for match in matches:
        if len(match) == 2:
            m, n = match
            if m.distance < ratio * n.distance:
                good.append(m)
    return good

import random

def get_pair(same=True):

    if same:
        # اختاري label عنده على الأقل 2 samples
        valid_labels = df_filtered["dx"].value_counts()
        valid_labels = valid_labels[valid_labels >= 2].index

        if len(valid_labels) == 0:
            raise ValueError("No class has at least 2 samples")

        label = random.choice(valid_labels)

        subset = df_filtered[df_filtered["dx"] == label].sample(2)
        return subset.iloc[0], subset.iloc[1]

    else:
        r1 = df_filtered.sample(1).iloc[0]

        # تأكد إن فيه classes مختلفة
        diff = df_filtered[df_filtered["dx"] != r1["dx"]]

        if len(diff) == 0:
            raise ValueError("No different class available")

        r2 = diff.sample(1).iloc[0]

        return r1, r2
def load_img(row):
    _, _, _, cleaned = preprocess_image(row["image_path"])
    return cleaned.astype(np.uint8)

# SIFT VIZ 1 - Keypoints: With vs Without Mask
fig, axes = plt.subplots(3, 3, figsize=(14, 12))
for i in range(3):
    img = results[i]["cleaned"].astype(np.uint8)
    kp1, _ = get_sift(img, use_mask=False)
    kp2, _ = get_sift(img, use_mask=True)
    mask   = get_segmentation_mask(img)

    axes[i, 0].imshow(mask, cmap='gray'); axes[i, 0].set_title(f"Mask ({results[i]['label']})"); axes[i, 0].axis("off")
    axes[i, 1].imshow(cv2.drawKeypoints(img, kp1, None, flags=4)); axes[i, 1].set_title(f"No Mask ({len(kp1)} kp)");   axes[i, 1].axis("off")
    axes[i, 2].imshow(cv2.drawKeypoints(img, kp2, None, flags=4)); axes[i, 2].set_title(f"With Mask ({len(kp2)} kp)"); axes[i, 2].axis("off")

plt.suptitle("SIFT Keypoints: With vs Without Mask", fontsize=14)
plt.tight_layout()
plt.show()


# SIFT VIZ 2 - Same vs Different Class Matching (FIXED)

same_scores, diff_scores = [], []

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

for idx, (same, store) in enumerate([(True, same_scores), (False, diff_scores)]):

    r1, r2 = get_pair(same)

    i1, i2 = load_img(r1), load_img(r2)

    k1, d1 = get_sift(i1, use_mask=True)
    k2, d2 = get_sift(i2, use_mask=True)

    # 🛑 skip لو مفيش features
    if d1 is None or d2 is None or len(k1) == 0 or len(k2) == 0:
        continue

    matches = get_matches(d1, d2)

    score = len(matches) / max(len(k1), len(k2))

    store.append(score)

    # 🎨 رسم النتائج
    img_matches = cv2.drawMatches(i1, k1, i2, k2, matches[:50], None, flags=2)

    axes[idx].imshow(img_matches)
    axes[idx].set_title(
        f"{'Same' if same else 'Different'} Class\n"
        f"{r1['dx']} vs {r2['dx']}\n"
        f"Matches: {len(matches)} | Score: {score:.3f}"
    )
    axes[idx].axis("off")

plt.suptitle("SIFT Matching ", fontsize=14)
plt.tight_layout()
plt.show()
# SIFT EVALUATION - FIXED

same_scores, diff_scores = [], []

for _ in range(20):
    for same, store in [(True, same_scores), (False, diff_scores)]:

        r1, r2 = get_pair(same)

        i1, i2 = load_img(r1), load_img(r2)

        k1, d1 = get_sift(i1, use_mask=True)
        k2, d2 = get_sift(i2, use_mask=True)

        # 🛑 skip invalid cases
        if d1 is None or d2 is None or len(k1) == 0 or len(k2) == 0:
            continue

        matches = get_matches(d1, d2)

        score = len(matches) / max(len(k1), len(k2))

        store.append(score)
        
summary = pd.DataFrame({
    "Pair Type": ["Same Class", "Different Class"],
    "Avg Score": [np.mean(same_scores), np.mean(diff_scores)],
    "Max Score": [np.max(same_scores),  np.max(diff_scores)],
    "Min Score": [np.min(same_scores),  np.min(diff_scores)],
})
print(summary.to_string(index=False))

plt.bar(["Same Class", "Diff Class"],
        [np.mean(same_scores), np.mean(diff_scores)],
        color=["steelblue", "tomato"])
plt.title("SIFT Avg Matching Score")
plt.ylabel("Score (0-1)")
plt.tight_layout()
plt.show()

img = cv2.imread(df_filtered.iloc[0]["image_path"])
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

keypoints, descriptors = get_sift(img)

print("Number of keypoints:", len(keypoints))
print("Descriptor shape:", descriptors.shape)

"""## Texture features (GLCM + LBP)"""

def extract_glcm_features(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    glcm = graycomatrix(gray, distances=[1],
                        angles=[0, np.pi/4, np.pi/2, 3*np.pi/4],
                        levels=256, symmetric=True, normed=True)
    features = {}
    for prop in ['contrast', 'homogeneity', 'energy', 'correlation']:
        features[f'glcm_{prop}'] = np.mean(graycoprops(glcm, prop))
    return features


def extract_lbp_features(img):
    gray          = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    mask          = get_segmentation_mask(img)
    lbp           = local_binary_pattern(gray, 24, 3, method='uniform')
    lesion_pixels = lbp[mask == 255]

    hist, _ = np.histogram(lesion_pixels, bins=26, range=(0, 26), density=True)

    features = {f'lbp_bin_{i}': hist[i] for i in range(26)}
    features['lbp_mean']    = np.mean(lesion_pixels)
    features['lbp_std']     = np.std(lesion_pixels)
    features['lbp_entropy'] = -np.sum(hist * np.log2(hist + 1e-10))

    return features, lbp, mask

def extract_shape_features(img):
    mask        = get_segmentation_mask(img)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return {'area': 0, 'perimeter': 0, 'circularity': 0,
                'solidity': 0, 'aspect_ratio': 0}

    c         = max(contours, key=cv2.contourArea)
    area      = cv2.contourArea(c)
    perimeter = cv2.arcLength(c, True)
    hull_area = cv2.contourArea(cv2.convexHull(c))
    _, _, w, h = cv2.boundingRect(c)

    return {
        'area':         area,
        'perimeter':    perimeter,
        'circularity':  (4 * np.pi * area / perimeter ** 2) if perimeter > 0 else 0,
        'solidity':     area / hull_area if hull_area > 0 else 0,
        'aspect_ratio': w / h if h > 0 else 0
    }

"""## Shape features"""

def extract_shape_features(img):
    mask        = get_segmentation_mask(img)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return {'area': 0, 'perimeter': 0, 'circularity': 0,
                'solidity': 0, 'aspect_ratio': 0}

    c         = max(contours, key=cv2.contourArea)
    area      = cv2.contourArea(c)
    perimeter = cv2.arcLength(c, True)
    hull_area = cv2.contourArea(cv2.convexHull(c))
    _, _, w, h = cv2.boundingRect(c)

    return {
        'area':         area,
        'perimeter':    perimeter,
        'circularity':  (4 * np.pi * area / perimeter ** 2) if perimeter > 0 else 0,
        'solidity':     area / hull_area if hull_area > 0 else 0,
        'aspect_ratio': w / h if h > 0 else 0
    }

"""##Build features table"""

rows = []
for r in results:
    img  = r["cleaned"].astype(np.uint8)
    f    = {}
    f.update(extract_glcm_features(img))
    f.update(extract_lbp_features(img)[0])
    f.update(extract_shape_features(img))
    f["label"] = r["label"]
    rows.append(f)

feature_df = pd.DataFrame(rows)
print(f"Features extracted: {feature_df.shape}")
print(f"Classes: {feature_df['label'].value_counts().to_dict()}")
feature_df.head()

"""VISUALIZATIONS"""

# LBP: Full vs Lesion Only
fig, axes = plt.subplots(3, 4, figsize=(16, 10))
for i in range(3):
    img = results[i]["cleaned"].astype(np.uint8)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    _, lbp_map, mask = extract_lbp_features(img)
    lbp_lesion = np.where(mask == 255, lbp_map, 0)

    axes[i, 0].imshow(img);              axes[i, 0].set_title(f"Original ({results[i]['label']})"); axes[i, 0].axis("off")
    axes[i, 1].imshow(gray, cmap='gray');axes[i, 1].set_title("Grayscale");                         axes[i, 1].axis("off")
    axes[i, 2].imshow(lbp_map, cmap='jet');  axes[i, 2].set_title("LBP Full");                     axes[i, 2].axis("off")
    axes[i, 3].imshow(lbp_lesion, cmap='jet');axes[i, 3].set_title("LBP Lesion Only");              axes[i, 3].axis("off")

plt.suptitle("LBP Texture Maps", fontsize=14)
plt.tight_layout()
plt.show()

# GLCM Bar Chart
glcm_cols = [c for c in feature_df.columns if 'glcm' in c]
feature_df.groupby("label")[glcm_cols].mean().T.plot(kind='bar', figsize=(10, 4), colormap='tab10')
plt.title("GLCM Features by Class")
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()

# Shape

fig, axes = plt.subplots(3, 2, figsize=(10, 12))
for i in range(3):
    img = results[i]["cleaned"].astype(np.uint8)
    mask = get_segmentation_mask(img)
    overlay= img.copy()
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        c = max(contours, key=cv2.contourArea)
        cv2.drawContours(overlay, [c], -1, (255, 0, 0), 2)           # contour  = red
        cv2.drawContours(overlay, [cv2.convexHull(c)], -1, (0,255,0), 2) # hull = green
        x, y, w, h = cv2.boundingRect(c)
        cv2.rectangle(overlay, (x, y), (x+w, y+h), (0, 100, 255), 2)    # bbox = blue

    axes[i, 0].imshow(img);     axes[i, 0].set_title(f"Original ({results[i]['label']})"); axes[i, 0].axis("off")
    axes[i, 1].imshow(overlay); axes[i, 1].set_title("Contour / Hull / BBox");              axes[i, 1].axis("off")

plt.suptitle("Shape Feature Extraction", fontsize=14)
plt.tight_layout()
plt.show()

"""## Ready for Classification"""

print(f"\n feature_df is ready!")
print(f"   Shape  : {feature_df.shape}")
print(f"   Classes: {feature_df['label'].value_counts().to_dict()}")

"""Segmentation Engineer Module

***K-Means Segmentation***
"""

def kmeans_segmentation(img, K=2):

    image = img.copy()

    pixel_vals = image.reshape((-1, 3))
    pixel_vals = np.float32(pixel_vals)

    criteria = (cv2.TERM_CRITERIA_EPS +
                cv2.TERM_CRITERIA_MAX_ITER, 100, 0.2)

    _, labels, centers = cv2.kmeans(pixel_vals,
                                    K,
                                    None,
                                    criteria,
                                    10,
                                    cv2.KMEANS_RANDOM_CENTERS)

    centers = np.uint8(centers)
    segmented = centers[labels.flatten()]
    segmented = segmented.reshape(image.shape)

    gray = cv2.cvtColor(segmented, cv2.COLOR_RGB2GRAY)

    _, mask = cv2.threshold(gray, 0, 255,
                            cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    return segmented, mask

"""Threshold Segmentation"""

def threshold_segmentation(img):

    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    blurred = cv2.GaussianBlur(gray, (7, 7), 0)

    _, mask = cv2.threshold(blurred,
                            0,
                            255,
                            cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    return mask

"""IoU Metric"""

def compute_iou(mask1, mask2):

    mask1 = mask1 > 0
    mask2 = mask2 > 0

    intersection = np.logical_and(mask1, mask2).sum()
    union = np.logical_or(mask1, mask2).sum()

    return intersection / union if union != 0 else 0

"""Ground Truth"""

def get_gt(img):

    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    blurred = cv2.GaussianBlur(gray, (7,7), 0)

    _, th = cv2.threshold(blurred, 0, 255,
                          cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    contours, _ = cv2.findContours(th,
                                   cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)

    contour_mask = np.zeros_like(gray)
    cv2.drawContours(contour_mask, contours, -1, 255, -1)

    mask = np.zeros(img.shape[:2], np.uint8)

    bgdModel = np.zeros((1,65), np.float64)
    fgdModel = np.zeros((1,65), np.float64)

    h, w = img.shape[:2]
    rect = (int(w*0.1), int(h*0.1), int(w*0.8), int(h*0.8))

    cv2.grabCut(img, mask, rect,
                bgdModel, fgdModel,
                5, cv2.GC_INIT_WITH_RECT)

    grab_mask = np.where((mask==2)|(mask==0),
                         0, 255).astype('uint8')

    final_gt = cv2.bitwise_and(contour_mask, grab_mask)

    return final_gt

"""Dice + Precision + Recall"""

def dice_score(y_true, y_pred):
    y_true = y_true > 0
    y_pred = y_pred > 0

    inter = np.logical_and(y_true, y_pred).sum()
    return (2 * inter) / (y_true.sum() + y_pred.sum() + 1e-10)


def precision_score(y_true, y_pred):
    y_true = y_true > 0
    y_pred = y_pred > 0

    tp = np.logical_and(y_true, y_pred).sum()
    fp = np.logical_and(~y_true, y_pred).sum()

    return tp / (tp + fp + 1e-10)


def recall_score(y_true, y_pred):
    y_true = y_true > 0
    y_pred = y_pred > 0

    tp = np.logical_and(y_true, y_pred).sum()
    fn = np.logical_and(y_true, ~y_pred).sum()

    return tp / (tp + fn + 1e-10)

"""SEGMENTATION + EVALUATION"""

seg_results = []

for i in range(10):

    img = results[i]["cleaned"].astype(np.uint8)

    gt = get_gt(img)

    _, km = kmeans_segmentation(img)
    th = threshold_segmentation(img)

    seg_results.append({
        "image": img,
        "gt": gt,

        "kmeans": km,
        "threshold": th,

        "km_iou": compute_iou(gt, km),
        "th_iou": compute_iou(gt, th),

        "km_dice": dice_score(gt, km),
        "th_dice": dice_score(gt, th),

        "km_prec": precision_score(gt, km),
        "th_prec": precision_score(gt, th),

        "km_rec": recall_score(gt, km),
        "th_rec": recall_score(gt, th),
    })

"""REPORT"""

report = pd.DataFrame({
    "Method": ["KMeans", "Threshold"],

    "IoU": [
        np.mean([r["km_iou"] for r in seg_results]),
        np.mean([r["th_iou"] for r in seg_results])
    ],

    "Dice": [
        np.mean([r["km_dice"] for r in seg_results]),
        np.mean([r["th_dice"] for r in seg_results])
    ],

    "Precision": [
        np.mean([r["km_prec"] for r in seg_results]),
        np.mean([r["th_prec"] for r in seg_results])
    ],

    "Recall": [
        np.mean([r["km_rec"] for r in seg_results]),
        np.mean([r["th_rec"] for r in seg_results])
    ]
})

print("FINAL SEGMENTATION REPORT:-\n")
print(report)

"""COMPARISON GRAPH"""

metrics = ["IoU", "Dice", "Precision", "Recall"]

kmeans_vals = [
    np.mean([r["km_iou"] for r in seg_results]),
    np.mean([r["km_dice"] for r in seg_results]),
    np.mean([r["km_prec"] for r in seg_results]),
    np.mean([r["km_rec"] for r in seg_results])
]

th_vals = [
    np.mean([r["th_iou"] for r in seg_results]),
    np.mean([r["th_dice"] for r in seg_results]),
    np.mean([r["th_prec"] for r in seg_results]),
    np.mean([r["th_rec"] for r in seg_results])
]

x = np.arange(len(metrics))

plt.figure(figsize=(10,5))

plt.bar(x - 0.2, kmeans_vals, width=0.4, label="KMeans")
plt.bar(x + 0.2, th_vals, width=0.4, label="Threshold")

plt.xticks(x, metrics)
plt.title("Segmentation Methods Comparison")
plt.ylabel("Score")
plt.legend()
plt.show()

"""Segmentation Grid"""

def show_segmentation(seg_results, n=3):

    plt.figure(figsize=(16, n * 4))

    for i in range(n):

        r = seg_results[i]

        imgs = [
            ("Original", r["image"]),
            ("Ground Truth", r["gt"]),
            ("KMeans", r["kmeans"]),
            ("Threshold", r["threshold"])
        ]

        for j, (title, img) in enumerate(imgs):

            plt.subplot(n, 4, i * 4 + j + 1)

            if len(img.shape) == 2:
                plt.imshow(img, cmap='gray')
            else:
                plt.imshow(img)

            plt.title(title, fontsize=11, fontweight='bold')
            plt.axis("off")

    plt.tight_layout()
    plt.show()

show_segmentation(seg_results, n=10)

"""Metric Heatmap"""

import seaborn as sns

def metrics_heatmap(seg_results):

    data = {
        "KMeans": [
            np.mean([r["km_iou"] for r in seg_results]),
            np.mean([r["km_dice"] for r in seg_results]),
            np.mean([r["km_prec"] for r in seg_results]),
            np.mean([r["km_rec"] for r in seg_results])
        ],
        "Threshold": [
            np.mean([r["th_iou"] for r in seg_results]),
            np.mean([r["th_dice"] for r in seg_results]),
            np.mean([r["th_prec"] for r in seg_results]),
            np.mean([r["th_rec"] for r in seg_results])
        ]
    }

    df_heat = pd.DataFrame(
        data,
        index=["IoU", "Dice", "Precision", "Recall"]
    )

    plt.figure(figsize=(7,5))
    sns.heatmap(df_heat, annot=True, cmap="YlGnBu", fmt=".3f")

    plt.title("Segmentation Performance Heatmap")
    plt.show()

metrics_heatmap(seg_results)

"""Per-Image Performance Trend"""

def per_image_trend(seg_results):

    iou_km = [r["km_iou"] for r in seg_results]
    iou_th = [r["th_iou"] for r in seg_results]

    plt.figure(figsize=(10,5))

    plt.plot(iou_km, marker='o', label="KMeans IoU")
    plt.plot(iou_th, marker='o', label="Threshold IoU")

    plt.title("IoU per Image Comparison")
    plt.xlabel("Image Index")
    plt.ylabel("IoU Score")
    plt.legend()
    plt.grid(True)

    plt.show()

per_image_trend(seg_results)

"""Classification Engineer Module (Naive Bayes + Boosting)

Prepare Dataset (Features + Labels)
"""

df_filtered["label"] = df_filtered["dx"].apply(lambda x: 0 if x == "nv" else 1)

def preprocess(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # CLAHE enhancement
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l,a,b = cv2.split(lab)

    clahe = cv2.createCLAHE(2.0, (8,8))
    l = clahe.apply(l)

    img = cv2.cvtColor(cv2.merge((l,a,b)), cv2.COLOR_LAB2RGB)

    # Hair removal
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (15,15))
    blackhat = cv2.morphologyEx(gray, cv2.MORPH_BLACKHAT, kernel)

    _, mask = cv2.threshold(blackhat, 10, 255, cv2.THRESH_BINARY)
    img = cv2.inpaint(img, mask, 3, cv2.INPAINT_TELEA)

    return img

def crop(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    blur = cv2.GaussianBlur(gray, (7,7), 0)

    _, mask = cv2.threshold(blur, 0, 255,
                            cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    contours,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        c = max(contours, key=cv2.contourArea)
        x,y,w,h = cv2.boundingRect(c)
        img = img[y:y+h, x:x+w]

    return cv2.resize(img, (128,128))

from skimage.feature import hog, local_binary_pattern, graycomatrix, graycoprops

def extract_features(img):

    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # HOG
    hog_feat = hog(gray, pixels_per_cell=(16,16),
                   cells_per_block=(2,2),
                   feature_vector=True)

    # LBP
    lbp = local_binary_pattern(gray, 24, 3, method='uniform')
    lbp_hist, _ = np.histogram(lbp, bins=26, range=(0,26), density=True)

    # GLCM
    glcm = graycomatrix(gray, [1], [0], 256, symmetric=True, normed=True)

    contrast = graycoprops(glcm, 'contrast')[0,0]
    energy   = graycoprops(glcm, 'energy')[0,0]

    # Color features
    color = img.mean(axis=(0,1))

    return np.hstack([hog_feat[:80], lbp_hist, [contrast, energy], color])

X, y = [], []

sample_size = min(700, len(df_filtered))
sample_df = df_filtered.sample(min(300, len(df_filtered)), random_state=42)

for _, row in sample_df.iterrows():

    img = preprocess(row["image_path"])
    img = crop(img)

    feat = extract_features(img)

    X.append(feat)
    y.append(row["label"])

X = np.array(X)
y = np.array(y)

from sklearn.feature_selection import SelectKBest, f_classif

scaler = StandardScaler()
X = scaler.fit_transform(X)

selector = SelectKBest(f_classif, k=25)
X = selector.fit_transform(X, y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    stratify=y,
    random_state=42
)

sm = SMOTE(sampling_strategy=1.0, random_state=42)
X_train, y_train = sm.fit_resample(X_train, y_train)

nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)

base = DecisionTreeClassifier(
    max_depth=2,
    min_samples_split=10
)

boost = AdaBoostClassifier(
    estimator=base,
    n_estimators=150,
    learning_rate=0.1,
    random_state=42
)

boost.fit(X_train, y_train)
probs = boost.predict_proba(X_test)[:, 1]

best_f1 = 0
best_t = 0.5

for t in np.arange(0.45, 0.85, 0.005):

    pred = (probs > t).astype(int)

    f1 = f1_score(y_test, pred)

    if f1 > best_f1:
        best_f1 = f1
        best_t = t

print("Best Threshold:", best_t)

boost_pred = (probs > best_t).astype(int)

def eval(y_true, y_pred):

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred)
    }

nb_res = eval(y_test, nb_pred)
boost_res = eval(y_test, boost_pred)

def plot_cm(y_true, y_pred, title):

    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

    plt.title(title)
    plt.show()

plot_cm(y_test, nb_pred, "Naive Bayes")

plot_cm(y_test, boost_pred, "AdaBoost")

def evaluate(y_true, y_pred):

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1-score": f1_score(y_true, y_pred)
    }

nb_res = evaluate(y_test, nb_pred)
boost_res = evaluate(y_test, boost_pred)

report = pd.DataFrame({
    "Model": ["Naive Bayes", "AdaBoost"],
    "Accuracy": [nb_res["Accuracy"], boost_res["Accuracy"]],
    "Precision": [nb_res["Precision"], boost_res["Precision"]],
    "Recall": [nb_res["Recall"], boost_res["Recall"]],
    "F1-score": [nb_res["F1-score"], boost_res["F1-score"]],
})

print("\nFINAL HIGH PERFORMANCE REPORT :-")
print(report)

plt.figure(figsize=(7,4))
sns.heatmap(report.set_index("Model"), annot=True, cmap="YlGnBu", fmt=".3f")
plt.title("Performance Heatmap")
plt.show()

from sklearn.metrics import roc_curve, auc

probs = boost.predict_proba(X_test)[:,1]

fpr, tpr, _ = roc_curve(y_test, probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AdaBoost (AUC = {roc_auc:.2f})")
plt.plot([0,1],[0,1],'--')

plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid()
plt.show()

from sklearn.metrics import roc_curve, auc

nb_probs = nb.predict_proba(X_test)[:,1]
boost_probs = boost.predict_proba(X_test)[:,1]

fpr_nb, tpr_nb, _ = roc_curve(y_test, nb_probs)
fpr_boost, tpr_boost, _ = roc_curve(y_test, boost_probs)

auc_nb = auc(fpr_nb, tpr_nb)
auc_boost = auc(fpr_boost, tpr_boost)

plt.figure(figsize=(6,5))

plt.plot(fpr_nb, tpr_nb, label=f"Naive Bayes (AUC={auc_nb:.2f})")
plt.plot(fpr_boost, tpr_boost, label=f"AdaBoost (AUC={auc_boost:.2f})")

plt.plot([0,1],[0,1],'--')

plt.title("ROC Curve Comparison")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(6,4))

plt.hist(nb_probs, bins=20, alpha=0.5, label="Naive Bayes")
plt.hist(boost_probs, bins=20, alpha=0.5, label="AdaBoost")

plt.title("Prediction Probability Distribution")
plt.legend()
plt.show()

errors = (y_test != boost_pred)

plt.figure(figsize=(6,4))
plt.scatter(range(len(y_test)), y_test, label="True", alpha=0.6)
plt.scatter(range(len(y_test)), boost_pred, label="Predicted", alpha=0.6)

plt.title("AdaBoost Error Analysis")
plt.legend()
plt.show()